CREATE TABLE `visitors` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ipAddress` VARCHAR(40) NOT NULL,
  `system` VARCHAR(20) NOT NULL,
  `browser` VARCHAR(20) NOT NULL,
  `added` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;