export const environment = {
  production: true,
  apiUrl: "192.168.1.100:3201",
  CACHE_ACCESSPOINTS: 'ACCESSPOINTS_ARRAY',
  CACHE_CHART_SECURITY: 'CHART_SECURITY',
  CACHE_CHART_FREQUENCY: 'CHART_FREQUENCY',
  CACHE_CHART_AREA: 'CHART_AREA',
  CACHE_CHART_BRANDS: 'CHART_BRANDS',
  CACHE_JWT: 'JWT'
};
